### ISSUE TITLE
process.version is undefined

### ISSUE THREAD

**Issue by Shujee** [moxystudio/node-cross-spawn#149]
The following line in in enoent.js:

`var isNode10 = process.version.indexOf('v0.10.') === 0;`

says that `process.version` is undefined. I'm using this in a Vue/Typescript project. This happens when I do `npm run serve`. It builds and loads fine, but throws this exception when the page is opened in the browser (MS Edge).

![image](https://user-images.githubusercontent.com/5603658/145770910-7d2a55bb-ffc6-4bda-975e-e7e95d7bfaa9.png)

**Comment by webketje** [comment]
[`process.version`](https://nodejs.org/api/process.html#processversion) is a correct assumption.
it makes absolutely no sense that this library is loaded in the browser.
Maybe you added it in package.json `dependencies` instead of `devDependencies`? In any case something is wrong with the tooling/bundling at your end

**Comment by Shujee** [comment]
Thanks. Later I found that this library is supposed to be used in Node environment on the server-side. I had added it to a VueJS project thinking that it is a normal client-side JS library (like axios), which was causing the trouble. I then found PDF.js which is an actual client-side lib that can convert PDF files to images.
